jujun-backend/config/routes.rb
JujunBackend::Application.routes.draw do

  resources :developers do
    resources :games do
      resources :game_sessions
    end
  end
  resources :players

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "admin/dashboard#index"

end

jujun-backend/app/models/admin_user.rb
class AdminUser
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

jujun-backend/app/models/developer.rb
class Developer
  include Mongoid::Document

  # Attributes
  field :name,    :type => String
  field :country, :type => String

  # permalink
  key :name

  validates :name,        :presence => true,
                          :uniqueness => { :case_sensitive => true }

  attr_accessible :name, :games

  has_many :games, :dependent => :destroy
end

jujun-backend/app/models/game.rb
class Game
  include Mongoid::Document

  # Attributes
  field :name
  field :genre
  field :plattforms
  field :release_year, :type => Integer


  # permalink
  key :name


  validates :name,  :presence => true,
                    :uniqueness => {:case_sensitive => true}

  attr_accessible :name, :genre, :plattforms, :release_year

  belongs_to  :developer
  has_many    :game_sessions, :dependent => :destroy
end

jujun-backend/app/models/game_session.rb
class GameSession
  include Mongoid::Document

  field :number_of_players, :type => Integer
  field :players
  field :game_data
  field :next_player
  field :game_status
  field :game_sessions

  belongs_to :game
end

jujun-backend/app/models/player.rb
class Player
  include Mongoid::Document
end

jujun-backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

jujun-backend/app/controllers/developers_controller.rb
class DevelopersController < InheritedResources::Base
  def index
    @developers = Developer.all
  end
end

jujun-backend/app/controllers/game_sessions_controller.rb
class GameSessionsController < InheritedResources::Base
end

jujun-backend/app/controllers/games_controller.rb
class GamesController < InheritedResources::Base
  def index
    @games = Game.find(params[:developer_id])
  end
end

jujun-backend/app/controllers/players_controller.rb
class PlayersController < InheritedResources::Base
end

jujun-backend/app/helpers/application_helper.rb
module ApplicationHelper
end

jujun-backend/app/helpers/developers_helper.rb
module DevelopersHelper
end

jujun-backend/app/helpers/game_sessions_helper.rb
module GameSessionsHelper
end

jujun-backend/app/helpers/games_helper.rb
module GamesHelper
end

jujun-backend/app/helpers/players_helper.rb
module PlayersHelper
end

jujun-backend/app/views/developers/_form.html.haml
= form_for @developer do |f|
  - if @developer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@developer.errors.count, "error")} prohibited this developer from being saved:"
      %ul
        - @developer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

jujun-backend/app/views/developers/edit.html.haml
%h1 Editing developer

= render 'form'

= link_to 'Show', @developer
\|
= link_to 'Back', developers_path

jujun-backend/app/views/developers/index.html.haml
%h1 Listing developers

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @developers.each do |developer|
    %tr
      %td= developer.name
      %td= link_to 'Show', developer
      %td= link_to 'Edit', edit_developer_path(developer)
      %td= link_to 'Destroy', developer, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Developer', new_developer_path

jujun-backend/app/views/developers/new.html.haml
%h1 New developer

= render 'form'

= link_to 'Back', developers_path

jujun-backend/app/views/developers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @developer.name

= link_to 'Edit', edit_developer_path(@developer)
\|
= link_to 'Back', developers_path

jujun-backend/app/views/game_sessions/_form.html.haml
= form_for @game_session do |f|
  - if @game_session.errors.any?
    #error_explanation
      %h2= "#{pluralize(@game_session.errors.count, "error")} prohibited this game_session from being saved:"
      %ul
        - @game_session.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

jujun-backend/app/views/game_sessions/edit.html.haml
%h1 Editing game_session

= render 'form'

= link_to 'Show', @game_session
\|
= link_to 'Back', game_sessions_path

jujun-backend/app/views/game_sessions/index.html.haml
%h1 Listing game_sessions

%table
  %tr
    %th
    %th
    %th

  - @game_sessions.each do |game_session|
    %tr
      %td= link_to 'Show', game_session
      %td= link_to 'Edit', edit_game_session_path(game_session)
      %td= link_to 'Destroy', game_session, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Game session', new_game_session_path

jujun-backend/app/views/game_sessions/new.html.haml
%h1 New game_session

= render 'form'

= link_to 'Back', game_sessions_path

jujun-backend/app/views/game_sessions/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_game_session_path(@game_session)
\|
= link_to 'Back', game_sessions_path

jujun-backend/app/views/games/_form.html.haml
= form_for @game do |f|
  - if @game.errors.any?
    #error_explanation
      %h2= "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      %ul
        - @game.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

jujun-backend/app/views/games/edit.html.haml
%h1 Editing game

= render 'form'

= link_to 'Show', @game
\|
= link_to 'Back', games_path

jujun-backend/app/views/games/index.html.haml
%h1 Listing games

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @games.each do |game|
    %tr
      %td= game.name
      %td= link_to 'Show', game
      %td= link_to 'Edit', edit_game_path(game)
      %td= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Game', new_game_path

jujun-backend/app/views/games/new.html.haml
%h1 New game

= render 'form'

= link_to 'Back', games_path

jujun-backend/app/views/games/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @game.name

= link_to 'Edit', edit_game_path(@game)
\|
= link_to 'Back', games_path

jujun-backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JujunBackend</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

jujun-backend/app/views/players/_form.html.haml
= form_for @player do |f|
  - if @player.errors.any?
    #error_explanation
      %h2= "#{pluralize(@player.errors.count, "error")} prohibited this player from being saved:"
      %ul
        - @player.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

jujun-backend/app/views/players/edit.html.haml
%h1 Editing player

= render 'form'

= link_to 'Show', @player
\|
= link_to 'Back', players_path

jujun-backend/app/views/players/index.html.haml
%h1 Listing players

%table
  %tr
    %th
    %th
    %th

  - @players.each do |player|
    %tr
      %td= link_to 'Show', player
      %td= link_to 'Edit', edit_player_path(player)
      %td= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Player', new_player_path

jujun-backend/app/views/players/new.html.haml
%h1 New player

= render 'form'

= link_to 'Back', players_path

jujun-backend/app/views/players/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_player_path(@player)
\|
= link_to 'Back', players_path